### ISSUE TITLE
Strona do testowania aktywności filtrów

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters.netlify.com#10]

**Comment by krystian3w** [comment]
u mnie wykrywa Nano Adblockera dla Firefox jako AdBlock / Adblock Plus, jakby za późno włączał się `set-constant.js`?

**Comment by hawkeye116477** [comment]
Poprawione, zamieniłem `pafdetect` na `pafDetect` i o dziwo, zaskoczyło.

**Comment by krystian3w** [comment]
@hawkeye116477  dalej jakiś konflikt nazw z wielkością liter?

**Comment by hawkeye116477** [comment]
@krystian3w Nie, wszystko jest ok.

**Comment by krystian3w** [comment]
Mnie chodzi czy dalej `set-constant` się buguje i niby scriptlet dalej wymaga dużego `D` bo coś tam z 🌲 / 🎄 się urwało.
