### ISSUE TITLE
dziwne przekierowanie

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishAnnoyanceFilters.netlify.com#9]
coś ostatnio generowało dziwne linki:

`https://polishannoyancefilters.netlify.com/issues/issues/thanks`

> Page Not found
> Looks like you've followed a broken link or entered a URL that doesn't exist on this site.
> 
>  Back to our site

zamiast

`https://polishannoyancefilters.netlify.com/issues/thanks` i numerka z zgłoszeniem.

**Comment by hawkeye116477** [comment]
Numerek zgłoszeniowy powinien być wysłany na maila. A jeżeli chodzi o te przekierowanie, to sprawdziłem i u mnie jest ok :smile:.

Aktualizacja: Już wiem o co chodzi, jak się wchodzi do issues bez ukośnika na końcu to wtedy przekierowanie jest poprawne.
